runtime: java17
instance_class: B2

manual_scaling:
  instances: 3

#instance_class: B2
#
#basic_scaling:
#  max_instances: 5
#  idle_timeout: 5m

# instance_class: F2

# automatic_scaling:
#   min_instances: 1
#   max_instances: 5
#   target_cpu_utilization: 0.6
#   target_throughput_utilization: 0.6


env_variables:
  DATABASE_URL: "jdbc:mysql//my-server:3306/my-db"

handlers:
- url: /*
  script: this field is required, but ignored
  secure: always